server:
  port: 8090
spring:
  application:
    name: dmslearning
  jms:
    cache:
      enabled: false
  security:
    user:
      password: password
      name: user

content:
  service:
    url: http://localhost:8080
    security:
      basicAuth:
        username: admin
        password: admin

custom:
  using-sdk: true
  folder-name: mktest