spring:
  application:
    name: dmslearning

#  activemq:
#    broker-url: tcp://activemq-host:61616
#  jms:
#    cache:
#      enabled: false
#
#content:
#  service:
#    url: http://repository:8080
#    security:
#      basic Auth:
#        username:admin
#        password:admin
server:
  port: 8090
##folder name constant